title: VoucherCodes

date: 2014

background_color: F9F9F9

content: |

  The following selected work is just a small part of a 3 year role as a designer with Vouchercodes.co.uk. The website brings together the best voucher codes, 2-for-1 restaurant vouchers, printable vouchers, deals and sales for hundreds of leading online stores to help save the public money. 

  Throughout the 3 years, I was lucky enough to witness the company growing from 20 staff to 90, being acquired by retail giants RetailMeNot.Inc, going public on the stock market, shipping a fully responsive site, producing 2 highly successful native apps, uncountable marketing campaigns and a whole lot more.

001.jpg:
  layout: screen

002.jpg:
  layout: screen

003.jpg:
  layout: screen

003a.jpg:
  layout: screen

003b.jpg:
  layout: screen


004.jpg:
  layout: screen


005.jpg:
  layout: screen

006.jpg:
  layout: screen


007.jpg:
  layout: screen

008.jpg:
  layout: screen

fade.png:
  layout: cancel

meta: Extra Info

# Extra info heading #

detail: Years:

non_link: 2011/2014

# Extra info heading #

detail2: Client:

link_text2: VoucherCodes.co.uk

link2: http://www.vouchercodes.co.uk





