title: Student.com

date: 2016

background_color: F9F9F9


content: |
 
 Student.com aims to provide quality accommodation to the masses on a global scale. By having more verified rooms than any other business in the space, Student.com allows students to choose with absolute peace of mind, wherever they’re coming from. 
 
 During my time at Student.com I produced localised UI for the several products, supporting over 20 languages including an adapted China site. I hired and lead a talented team of designers whilst managing multiple stakeholders and advocating UX principles across the business. 

001.png:
  layout: screen


002.png:
  layout: screen


003.png:
  layout: mobile-1


004.png:
  layout: mobile-2


005.png:
  layout: screen


006.png:
  layout: screen


007.png:
  layout: screen


008.png:
  layout: screen


009.png:
  layout: mobile-1


010.png:
  layout: mobile-2


011.png:
  layout: screen


meta: Extra Info

# Extra info heading #

detail: Years:

non_link: 2015/2016

# Extra info heading #

detail2: Client:

link_text2: Student.com

link2: http://student.com


