title: UX / UI Design Process &  Workflow

date: 2012/2014

content: |

  The following is a short collection of images and screengrabs which collectively, give an insight into my design methods and workflows. Much of the work is taken from VoucherCodes.co.uk 'User Generated Content' and 'Save for Later' initiatives. 

000.png:
  layout: screen


001.jpg:
  layout: screen


002.jpg:
  layout: screen


004.jpg:
  layout: screen


005.jpg:
  layout: screen


006.png:
  layout: screen


007.png:
  layout: screen


008.png:
  layout: screen


011.png:
  layout: screen


011a.jpg:
  layout: screen


012.png:
  layout: screen


013.png:
  layout: screen


013a.jpg:
  layout: screen


013b.jpg:
  layout: screen


014.png:
  layout: screen


015.jpg:
  layout: screen


016.jpg:
  layout: screen

017.jpg:
  layout: screen

018.png:
  layout: screen

018a.png:
  layout: screen

018b.png:
  layout: screen

018c.png:
  layout: screen


018d.png:
  layout: screen


019.jpg:
  layout: screen

020.jpg:
  layout: screen

021.png:
  layout: screen

022.png:
  layout: screen

023.jpg:
  layout: screen

024.jpg:
  layout: screen


fade.png:
  layout: cancel











meta: Extra Info

# Extra info heading #

detail: Years:

non_link: 2012/2014

# Extra info heading #

detail2: Client:

non_link2: Various






