title: Portr Carry Goods

Date: 2013

background_color: 313131

content: |

  Portr Carry Goods came from an interest in leathercraft, knocking together wallets, card holders and camera straps in my spare time. I decided to create a rough brand so I may one day sell the limited runs online. The project is still ongoing, the following documents my progress, branding studies and one-off pieces. 


000.png:
  layout: screen

001.jpg:
  layout: screen

002.jpg:
  layout: screen

003.jpg:
  layout: screen


004.jpg:
  layout: screen


005.jpg:
  layout: screen

fade.jpg:
  layout: cancel

meta: Extra Info

# Extra info heading #

detail: Year:

non_link: 2013

# Extra info heading #

detail2: Client:

non_link2: N/A



# Extra info heading #

detail3: Tools:

non_link3: Illustrator, Linen Thread




